<a href="https://colab.research.google.com/github/Fabs00/FOG_AA/blob/main/Tarea_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv("/content/covid.csv")
df

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region,iso_alpha
0,USA,North America,3.311981e+08,5032179,NaN,162804.0,NaN,2576668.0,NaN,2292707.0,18296.0,15194.0,492.0,63139605.0,190640.0,Americas,USA
1,Brazil,South America,2.127107e+08,2917562,NaN,98644.0,NaN,2047660.0,NaN,771258.0,8318.0,13716.0,464.0,13206188.0,62085.0,Americas,BRA
2,India,Asia,1.381345e+09,2025409,NaN,41638.0,NaN,1377384.0,NaN,606387.0,8944.0,1466.0,30.0,22149351.0,16035.0,South-EastAsia,IND
3,Russia,Europe,1.459409e+08,871894,NaN,14606.0,NaN,676357.0,NaN,180931.0,2300.0,5974.0,100.0,29716907.0,203623.0,Europe,RUS
4,South Africa,Africa,5.938157e+07,538184,NaN,9604.0,NaN,387316.0,NaN,141264.0,539.0,9063.0,162.0,3149807.0,53044.0,Africa,ZAF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,Montserrat,North America,4.992000e+03,13,NaN,1.0,NaN,10.0,NaN,2.0,NaN,2604.0,200.0,61.0,12220.0,NaN,MSR
205,Caribbean Netherlands,North America,2.624700e+04,13,NaN,NaN,NaN,7.0,NaN,6.0,NaN,495.0,NaN,424.0,16154.0,NaN,
206,Falkland Islands,South America,3.489000e+03,13,NaN,NaN,NaN,13.0,NaN,0.0,NaN,3726.0,NaN,1816.0,520493.0,NaN,FLK
207,Vatican City,Europe,8.010000e+02,12,NaN,NaN,NaN,12.0,NaN,0.0,NaN,14981.0,NaN,NaN,NaN,Europe,VAT
208,Western Sahara,Africa,5.986820e+05,10,NaN,1.0,NaN,8.0,NaN,1.0,NaN,17.0,2.0,NaN,NaN,Africa,ESH

#Tarea en clase (2 puntos)
Aplica algún método de filtro a tus datos mediante el uso de SelectKBest

In [9]:
from sklearn.feature_selection import SelectKBest, f_classif

In [46]:
columnas =["ActiveCases","Serious,Critical",	"Tot Cases/1M pop",	"Deaths/1M pop",	"Tests/1M pop"]
selec_df = df[columnas]
selec = selec_df.fillna(selec_df.mean())
x = selec.values
columna =["TotalTests"]
selec_df1 = df[columna]
sele1 = selec_df1.fillna(selec_df1.mean())
y = sele1.values

array([[2.29270700e+06, 1.82960000e+04, 1.51940000e+04, 4.92000000e+02,
        1.90640000e+05],
       [7.71258000e+05, 8.31800000e+03, 1.37160000e+04, 4.64000000e+02,
        6.20850000e+04],
       [6.06387000e+05, 8.94400000e+03, 1.46600000e+03, 3.00000000e+01,
        1.60350000e+04],
       ...,
       [0.00000000e+00, 5.34393443e+02, 3.72600000e+03, 9.86811765e+01,
        5.20493000e+05],
       [0.00000000e+00, 5.34393443e+02, 1.49810000e+04, 9.86811765e+01,
        8.39593665e+04],
       [1.00000000e+00, 5.34393443e+02, 1.70000000e+01, 2.00000000e+00,
        8.39593665e+04]])

In [35]:
selector = SelectKBest(score_func=f_classif, k=5)
X_new = selector.fit_transform(x, y)
X_new

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([[2.29270700e+06, 1.82960000e+04, 1.51940000e+04, 4.92000000e+02,
        1.90640000e+05],
       [7.71258000e+05, 8.31800000e+03, 1.37160000e+04, 4.64000000e+02,
        6.20850000e+04],
       [6.06387000e+05, 8.94400000e+03, 1.46600000e+03, 3.00000000e+01,
        1.60350000e+04],
       ...,
       [0.00000000e+00, 5.34393443e+02, 3.72600000e+03, 9.86811765e+01,
        5.20493000e+05],
       [0.00000000e+00, 5.34393443e+02, 1.49810000e+04, 9.86811765e+01,
        8.39593665e+04],
       [1.00000000e+00, 5.34393443e+02, 1.70000000e+01, 2.00000000e+00,
        8.39593665e+04]])

#Tarea (8 puntos)
*  Aplica los modelos de selección de características cuidando los supuestos de cada modelo
*   Busca una o varias métricas para seleccionar características en literatura relacionada con tu problema (cita tus fuentes)
*   Con base en tu investigación, determina las características más relevantes de tu conjunto de datos
*   Discute por qué crees que las características seleccionadas son las más relevantes y por qué el resto quedaron excluidas en la selección

In [55]:
y00 = df[['TotalTests']].fillna(0)
x00 = df[["ActiveCases","Serious,Critical",	"Tot Cases/1M pop",	"Deaths/1M pop",	"Tests/1M pop"]].fillna(0)

In [56]:
from sklearn.feature_selection import f_regression
f_value = f_regression(x00, y00)
# Regresa arreglo de estadístico F y valor p
f_value

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

(array([746.18303217, 595.18526151,   8.40385542,  17.71471554,
          2.37541041]),
 array([1.42627967e-70, 8.27986817e-63, 4.14783216e-03, 3.82433463e-05,
        1.24786494e-01]))

Fuentes

*   https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8080943/
*   https://www.who.int/es/news-room/fact-sheets/detail/coronavirus-disease-(covid-19)
*   https://data.who.int/dashboards/covid19/cases?n=c
*   https://www.bbc.com/mundo/noticias-54347255{

De acuerdo a lo investigado, las principales caracteristiccas que encuentro son los test, casos y muertes por millon

Ya que al hacerlo por millón normalizamos la diferencia entre las distintas cantidades de poblaciones (aunque tendríamos que considerar también la concentración de vivienda)

Para saber si hay un número cosniderable de datos a considerar habría que tomar los test que se realizaron así no solo los que fueron registrados como casos activos