<a href="https://colab.research.google.com/github/Fabs00/FOG_AA/blob/main/Tarea_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tarea en clase

Cargar conjunto de datos mediante pandas

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/covid.csv")

Especificar el tipo de datos de cada columna

In [ ]:
df.info()

In [ ]:
df.head()

Si es necesario, asignar una columna como Ã­ndice

In [12]:
df['nuevo_indice'] = range(len(df))
df.set_index('nuevo_indice', inplace=True)

In [ ]:
df.head()

#Tarea

Crear, modificar o eliminar columnas

In [30]:
df_sin_columna = df.drop(columns=['NewDeaths'])
df_sin_columna

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region,iso_alpha
nuevo_indice,,,,,,,,,,,,,,,,
0,USA,North America,3.311981e+08,5032179,NaN,162804.0,2576668.0,NaN,2292707.0,18296.0,15194.0,492.0,63139605.0,190640.0,Americas,USA
1,Brazil,South America,2.127107e+08,2917562,NaN,98644.0,2047660.0,NaN,771258.0,8318.0,13716.0,464.0,13206188.0,62085.0,Americas,BRA
2,India,Asia,1.381345e+09,2025409,NaN,41638.0,1377384.0,NaN,606387.0,8944.0,1466.0,30.0,22149351.0,16035.0,South-EastAsia,IND
3,Russia,Europe,1.459409e+08,871894,NaN,14606.0,676357.0,NaN,180931.0,2300.0,5974.0,100.0,29716907.0,203623.0,Europe,RUS
4,South Africa,Africa,5.938157e+07,538184,NaN,9604.0,387316.0,NaN,141264.0,539.0,9063.0,162.0,3149807.0,53044.0,Africa,ZAF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,Montserrat,North America,4.992000e+03,13,NaN,1.0,10.0,NaN,2.0,NaN,2604.0,200.0,61.0,12220.0,NaN,MSR
205,Caribbean Netherlands,North America,2.624700e+04,13,NaN,NaN,7.0,NaN,6.0,NaN,495.0,NaN,424.0,16154.0,NaN,
206,Falkland Islands,South America,3.489000e+03,13,NaN,NaN,13.0,NaN,0.0,NaN,3726.0,NaN,1816.0,520493.0,NaN,FLK
207,Vatican City,Europe,8.010000e+02,12,NaN,NaN,12.0,NaN,0.0,NaN,14981.0,NaN,NaN,NaN,Europe,VAT
208,Western Sahara,Africa,5.986820e+05,10,NaN,1.0,8.0,NaN,1.0,NaN,17.0,2.0,NaN,NaN,Africa,ESH

Filtrar registros

In [ ]:
df.tail(10)

In [16]:
df.head(5)

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region,iso_alpha
nuevo_indice,,,,,,,,,,,,,,,,,
0,USA,North America,3.311981e+08,5032179,NaN,162804.0,NaN,2576668.0,NaN,2292707.0,18296.0,15194.0,492.0,63139605.0,190640.0,Americas,USA
1,Brazil,South America,2.127107e+08,2917562,NaN,98644.0,NaN,2047660.0,NaN,771258.0,8318.0,13716.0,464.0,13206188.0,62085.0,Americas,BRA
2,India,Asia,1.381345e+09,2025409,NaN,41638.0,NaN,1377384.0,NaN,606387.0,8944.0,1466.0,30.0,22149351.0,16035.0,South-EastAsia,IND
3,Russia,Europe,1.459409e+08,871894,NaN,14606.0,NaN,676357.0,NaN,180931.0,2300.0,5974.0,100.0,29716907.0,203623.0,Europe,RUS
4,South Africa,Africa,5.938157e+07,538184,NaN,9604.0,NaN,387316.0,NaN,141264.0,539.0,9063.0,162.0,3149807.0,53044.0,Africa,ZAF

Crear subconjutos de datos

In [26]:
subconjunto = df.loc[df["Deaths/1M pop"] > 100, ["Country/Region", "Continent"]]

In [ ]:
subconjunto

Crear grupos de datos

In [28]:
grupo = df.groupby("Continent")["TotalCases"].mean()

In [29]:
grupo

Continent
Africa                17752.052632
Asia                  97704.041667
Australia/Oceania      3622.500000
Europe                62137.000000
North America        169120.257143
South America        324519.500000
Name: TotalCases, dtype: float64